### ISSUE TITLE
Black shadow left behind when closing after $http call

### ISSUE THREAD

**Issue by rossrossp** [dwmkerr/angular-modal-service#205] opened 2017-03-12 23:22 UTC
When attempting to close a modal after a $http call, the black shadow gets left behind.
Has anybody else seen this?

`$http({ method : "POST", url : "/api/bla", data: { } })
.then(function mySuccess(response) { 
  if(response.data.error) { 
    $scope.errorMessage = response.data.error; 
  } else { 
    close(true, 500); 
  } }, function myError(response) { //bla });`

Any ideas?

**Comment by charyorde** [comment] 2017-04-23 20:41
+1

**Comment by aaronlifton2** [comment] 2017-04-29 00:12
I encountered this too, but fixed it by increasing the timeout on close()

**Comment by dwmkerr** [comment] 2017-05-20 11:06
The issue is that because the bootstrap button with `data-dismiss` is not being pressed, bootstrap is not removing the background. The key is to make sure that when you close the modal programatically (for bootstrap), you tell bootstrap to remove it. See:

https://github.com/dwmkerr/angular-modal-service#faq

I am currently working on a feature which makes this significantly easier, should be released later today

**Comment by dwmkerr** [comment] 2017-05-20 12:31
Resolved in https://github.com/dwmkerr/angular-modal-service/releases/tag/v0.12.0

You can now use the following option in your `showModal` call:

```js
ModalService.showModal({
  templateUrl: "some/bootstrap-template.html",
  controller: "SomeController",
  preClose: (modal) => { modal.element.modal('hide'); }
}).then(function(modal) {
  // etc
});
```

This will ensure the bootstrap modal is destroyed (as well as the backdrop) even if the modal is closed programatically (as it is in your case).

**Closed by dwmkerr** 2017-05-20 12:31 UTC
