### ISSUE TITLE
prevent close

### ISSUE THREAD

**Issue by maxdiable** [dwmkerr/angular-modal-service#55] opened 2015-03-22 15:21 UTC
hi, I want to decide when I close the modal, and that it is only the close button to close the modal, you can .

thank you

Massimo

**Comment by dwmkerr** [comment] 2015-03-23 08:59
Hi,

Please see the FAQ on the read me page. There is a section describing how
to close a bootstrap modal.

**Comment by josevillacreses** [comment] 2015-04-07 15:40
I'm having the same issue. I want to prevent closing the modal when clicking outside the modal.
What i find strange is that it works the way I want in the sample http://jsfiddle.net/dwmkerr/8MVLJ/

Using the same setup from the sample, but with different versions of js libraries, the modal closes when clicking outside.

Closing the bootstrap modal is not the issue, the problem is not closing it unless my "close()" function is called from the view.

**Comment by josevillacreses** [comment] 2015-04-08 17:36
In case someone finds this usefule, this is how I managed to prevent closing the modal:
Right before showing the modal with
                modal.element.modal();
set the modal like this
                $('#curvasModal').modal({
                    backdrop: 'static',
                    keyboard: true
                });
                modal.element.modal();

**Comment by lindamarieb** [comment] 2015-05-07 08:58
The only thing that worked for me was this:

    <div class="modal" data-backdrop="static" data-keyboard="false">

**Comment by ledgeJumper** [comment] 2015-06-08 03:44
@josevillacreses that worked for me, thanks!  FYI, you can do it in one call instead of the two you have.  So replace:

    modal.element.model();

with
    
    model.element.model({ 
        backdrop: 'static', 
        keyboard: false 
    });

[Here is a link to the bootstrap modal options.](http://getbootstrap.com/javascript/#modals-options) For those wondering it tells you what is being defaulted here. If the above solution *doesn't* work try to add in 'show: true' to the options to tell it to allow you to initialize and show it in one go.

**Comment by dwmkerr** [comment] 2017-05-20 13:35
Thanks everyone, I believe this is closed with @lindamarieb and @ledgeJumper's solutions. Now documented in the FAQS at:

https://github.com/dwmkerr/angular-modal-service#how-can-i-prevent-a-bootstrap-modal-from-being-closed

**Closed by dwmkerr** 2017-05-20 13:35 UTC
